### ISSUE TITLE
Return XHTML content as well (the Tika default) 

### ISSUE THREAD

**Issue by alxlo** [mattcg/node-tika#2]
It would be awesome, if the bridge could not only deliver plain text, but as well the XHTML that can be generated by the Tika default configuration :-)

**Comment by mattcg** [comment]
Hi @alxlo, out of interest, what is the use-case for XHTML output?

**Comment by alxlo** [comment]
Hi Matthew,
the XHTML contains a separate <div>-section for each page of a PDF file. I am currently experimenting with lunr.js to generate a search index on the server side to be used by a (mobile) client application and hope to deliver more precise search hits by indicating not only the PDF, but also the the page in the PDF for search hits.
Best regards, Alexander

**Comment by mattcg** [comment]
Try the `tika.xhtml` method available on the master branch. Be warned that there are breaking changes with the way options are specified.

**Comment by alxlo** [comment]
Thank you so much, works like a charme!

**Comment by mattcg** [comment]
Fantastic :smile_cat:
